### ISSUE TITLE
Does a model need to belong to a collection?

### ISSUE THREAD

**Issue by nickryall** [masylum/mobx-rest#1]
Does a model need to belong to a collection to gain the restful actions/methods? Or can you instantiate a single model and still call save() and expect it to work ( similar to backbone) ?

**Comment by masylum** [comment]
Its a good question. I should be able to simplify this indeed. I will let you know as I progress

**Comment by masylum** [comment]
I know it took me a little bit longer that you may have been expected but... It's already done!
From now on updates are going to be faster. We had this vendorized at factorialhr.com where we use `mobx-rest` in production. Now we brought it back here and we will be updating it more regulrly.

Enjoy!
