### ISSUE TITLE
Support for authentication

### ISSUE THREAD

**Issue by ax487** [masylum/mobx-rest#11]
I would like to use mobx-rest as a frontend for an API. Unfortunately, the API requires a key which is submitted using an additional header. Is there a way to include headers in the API adapter in order to send them with every request?

**Comment by masylum** [comment]
Sure thing. `mobx-rest` is transport agnostic. You can make your own adapter that fulfills your needs. A couple of examples are:

  - https://github.com/masylum/mobx-rest-jquery-adapter
  - https://github.com/masylum/mobx-rest-fetch-adapter

**Comment by ax487** [comment]
Well, I sort of see your point. However, I see the following problem:

The adapter is stored as a global variable. I am having a difficult time setting the adapter before any requests are made, in particular, the login is only triggered once the document becomes ready. I would like to pass a `Promise` in such a way that no query is performed until the promise is fulfilled. I can implement this functionality in the adapter, but I have a really hard time assuring that the adapter is set correctly before the first `Model` / `Collection` is constructed.

**Comment by masylum** [comment]
I'm not sure I understand the problem. Maybe if you had a gist it could help me understand better.

Do you feel `apiClient` abstraction is not good enough? Feel free to propose an API that would solve your needs and let's check together how could we bundle it 😃

**Comment by rdiazv** [comment]
I actually submitted masylum/mobx-rest-fetch-adapter/pull/1 for the same exact reason. The setup Isn't based on promises, but it works for me.

**Comment by masylum** [comment]
Will check this weekend :)

**Comment by masylum** [comment]
Is there anything pending to be done here? Reopen if this is still an issue
