### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by ax487** [masylum/mobx-rest#12]
I don't know if this should be treated as an error since everything seems to work, but there is a circular dependency in `mobx-rest`:

    mobx-rest/lib/Collection.js -> node_modules/mobx-rest/lib/Model.js -> node_modules/mobx-rest/lib/Collection.js

I found this using using a [dependency checker](https://www.npmjs.com/package/circular-dependency-plugin).

**Comment by masylum** [comment]
Good catch but not sure how to work around it and whether is necessary to do so. The dependency of `Model.js` towards `Collection.js` is only used for type checking although I can see that in the final build the require keeps being there.

**Comment by ax487** [comment]
Well, this broke my code at one point, so I just wanted to give you a heads up.
