### ISSUE TITLE
Semantic of save operation

### ISSUE THREAD

**Issue by ax487** [masylum/mobx-rest#13]
I just encountered the following  problem:

I have a model `Participant`. I tried calling `var promise = Participants.build().save()` in order to save an instance. I attached a callback to the Promise via `promise.then(onFulfilled, onRejected);`

I expected the promise to fail, i.e. to call `onRejected`. Instead the promise resolved, i.e. the `onFulfilled` function was called. The argument was a JSON response indicating errors. There was however no way of obtaining the actual response code or any notification regarding the fact that the request failed.

If this is a bug, could you fix it? If this is a feature, could you tell me how to distinguish between failed and successful requests?

I am using

    "mobx-rest": "^2.1.4",
    "mobx-rest-fetch-adapter": "0.0.5",

**Comment by masylum** [comment]
I understand the confusion. The semantics right now are that the IO operation was fulfilled. Saving was finished correctly and populated the object with `errors` if any. I find this less imperative than handling failure/success cases independently. Pseudocode example with React:


```js
function User ({ user }) {
  if (user.errors) return <span>{user.errors}</errors>
  if (user.request) return <img src='spinner.jpg' />
  return <span>{user.get('name')}</span>
}

class UserForm extends React.Component {
  onSubmit () {
    const { user } = this.props
    user.save()
  }

  render () {
    const { user } = this.props
    <Form onSubmit={this.onSubmit.bind(this)}>
      <User user={user} />
    </Form>
  }
}
