### ISSUE TITLE
mobxReact.apiClient is not a function

### ISSUE THREAD

**Issue by ighormartins** [masylum/mobx-rest#17]
I have a clean installation of react-native using the ignite generator with mobx boilerplate.

I followed all the steps to install mobx-rest and mobx-rest-fetch-adapter (Which is successfully installed), and added this to my rootContainer.js:

const apiPath = 'https://api.x.pt'
apiClient(adapter, { apiPath })

But I get this weird error, saying apiClient isn't a function.
Does mobx-rest support react-native?

![screen shot 2017-08-01 at 19 11 42](https://user-images.githubusercontent.com/1692791/28839972-4e4a9db8-76ed-11e7-90da-6f6ca19d40cd.png)

**Comment by masylum** [comment]
You have to import it!

```js
import { apiClient } from 'mobx-rest'
```
