### ISSUE TITLE
Dynamically setting Authorization header in requests

### ISSUE THREAD

**Issue by jzaefferer** [masylum/mobx-rest#18]
I'm currently testing mobx-rest in an app that uses the Authorization to authorize API requests for logged in users. The solution below is what I currently use, though I suspect that there's a better way.

Whatever the right solution, it needs some documentation - right now the docs for this project don't mention settings headers anywhere. With some feedback I'd be happy to help adding those docs.

This is what I have right now, to add the header when the user state changes:
```
function initApiClient() {
  const options = {
    apiPath: window.env.apiUrl,
  }
  if (me.isLoggedIn) {
    options.commonOptions = {
      headers: {
        Authorization: `Bearer ${me.token}`,
      },
    }
  }
  apiClient(adapter, options)
}

me.on('change', () => {
  initApiClient()
})
initApiClient()
```
`me` is not yet using MobX (or mobx-rest Model), though it shouldn't look much different.

**Comment by masylum** [comment]
You are right, this is how you use it. `apiClient` is poorly documented ATM. So with `apiClient` you can configure both the `apiPath` and the `commonOptions` like you did in that example. You can use it to set options for all requests although you can overwrite them for individual requests.

**Comment by jzaefferer** [comment]
Could you provide an example for overriding headers for individual requests? I tried that, but couldn't get it working.

With that I could put together a PR for documenting apiClient and setting headers in general.

**Comment by masylum** [comment]
I'm actually wrong, we haven't abilitiated that yet. It could be done easily in places such as this one: https://github.com/masylum/mobx-rest/blob/master/src/Collection.js#L291 but right now it's hardcoded to `options.data` instead of passing the whole `options`. I'm open to change that :)
