### ISSUE TITLE
Model attribute as a collection?

### ISSUE THREAD

**Issue by jzaefferer** [masylum/mobx-rest#23]
I've got a model with two attributes, one string label, one array of items. I'd like to represent the items as a collection, with its own Model and computed properties.

While attributes can be nested, they're basically a dumb JS object, no classes.

The only FAQ entry, https://github.com/masylum/mobx-rest#how-do-i-create-relations-between-the-models isn't helping, since that's model-to-model.

What I have in mind:
```
const data = {
  label: 'foobar',
  items: [
    {
      id: '1',
      label: 'something'
    },
    {
      id: '2',
      label: 'foobarrr'
    }
  ]
}
const model = new MyModel(data)
// fullLabel would be a computed property of the model of the items collection
model.get('items').get('1').fullLabel
```
Is there something in place already that I missed? Is there a different approach that would make more sense here?

**Comment by jzaefferer** [comment]
Both of these break down very quickly:
```
@computed get items() {
  return new Items(this.get('items'))
}
```
and
```
constructor(attributes) {
  super(attributes)
  this.items = new Items(attributes.items ? attributes.items : [])
}
```
In the latter attempt I ended up with a "RangeError: Maximum call stack size exceeded", from some "at runLazyInitializers", which turns out to be really difficult to debug.

I suspect there's a simple solution, but I'm not seeing it, yet...

**Comment by masylum** [comment]
`mobx-rest` does not fully support nested APIs. In my experience supporting nested API's is extremely difficult and painful. That being said, you can always use array attributes normally, but they won't behave as collections.

I highly recommend keeping your collections separated and relating them between them. This way you treat your stores as if they where SQL tables. This is how we do it at Factorial:

```js
class Comment extends Model {}
class Comments extends Collection {
  url () {
    return `/comments`
  }

  model () {
    return Comment
  }
}

class Post extends Model {
  @computed
  get comments () {
    return comments.find({ post_id: this.get('id') })
  }
}

const post = new Post({ id: 1 })
const comments = new Comments()

// Fetch only comments for that given post
comments.fetch({ data: { post_id: post.get('id') } })

comments.models.length === 0
post.comments // => return an array of Comment
post.comments.length === 0

comments.create([
  { post_id: 1, body: 'foo' },
  { post_id: 2, body: 'bar' }
])

comments.models.length === 2
post.comments.length === 1
post.comments[0].get('body') === 'foo'
```

(disclaimer, I didn't test the code above and may be wrong, but it will give you an idea)

**Comment by jzaefferer** [comment]
> That being said, you can always use array attributes normally, but they won't behave as collections.

That's what I ended up with. Looks a bit like this:
```
export class SomeModel extends Model {
  constructor(attributes) {
    super(Object.assign({
      items: [],
    }, attributes))
  }
  @computed get items() {
    return this.get('items')
  }
  @action removeItem(item) {
    this.items.splice(this.items.indexOf(item), 1)
  }
}
```
Since the items here aren't a proper collections (they have no identity), that seems like the correct approach.

Do you think this could be useful for others, and should make it into the readme?

I think your Post/Comments example has its use as well. I didn't know I could pass `data` to `fetch()`.

**Comment by masylum** [comment]
Yes, I will update the README with the missing information.

**Comment by masylum** [comment]
Already updated the readme with that information :)
