### ISSUE TITLE
lodash is a liability (bundle size)

### ISSUE THREAD

**Issue by ryedin** [masylum/mobx-rest#30]
I'm analyzing my application's bundle size, and the biggest contributor to file size is `mobx-rest`, but only because of the 3 methods you use from `lodash` in `src/Model.js`. 

```import { uniqueId, isString, debounce } from 'lodash'```

This makes the entire lodash library get included in the bundle (roughly .5MB un-minified).

Please consider either removing the lodash dependency altogether, or importing these three methods directly via:
```
import uniqueId from 'lodash/uniqueId'
import isString from 'lodash/isString'
import debounce from 'lodash/debounce'
```
which will allow for a much smaller bundle size

**Comment by jzaefferer** [comment]
As a user and occasional contributor: Yes please! Could you try to put together a Pull Request for that?

**Comment by ryedin** [comment]
@jzaefferer working on it...

**Comment by ryedin** [comment]
oops, missed these in `src/Collection.js` in initial comment:

```import {
  isEmpty,
  filter,
  isMatch,
  find,
  difference,
  debounce,
  map,
  last
} from 'lodash'```
