### ISSUE TITLE
setup tests in jest with mobx-rest 

### ISSUE THREAD

**Issue by n1arash** [masylum/mobx-rest#34]
how to setup tests in jest with mobx-rest ?
i get adapter is not Defined in errors 
after setting up adapter in setupTest file i get Error : 
`Cannot Read Property of Object.Prototype of undefined`
i will appericiate if you give me example of testing a component

**Comment by andresgutgon** [comment]
Did you setup adapter in your project?

```javascript
import adapter from 'mobx-rest-fetch-adapter'
import { apiClient } from 'mobx-rest'

// We will use the adapter to make the `xhr` calls
apiClient(adapter, { apiPath: '/api' })
/...
```

**Comment by n1arash** [comment]
i fixed that problem :+1: 
now there is new problem Model.fetch() method not resolve in test and i don't get data from my Model so all of my data is undefined for example with `Model.get('id')` i get: 
`cannot find Attribute "id" of Undefined`

**Comment by andresgutgon** [comment]
Do you really need to test `fetch`? Does already tested on mobx-rest

**Comment by n1arash** [comment]
i don't want test fetch i just want fetch data from API and take response in results

**Comment by andresgutgon** [comment]
If you just want data on your collection you can do it in this way:

``` javascript
// Jest spec
let myCollection
beforeEach(() => {
   myMobexRestCollection.add([
     {id: 'my-fake-id-1, name: 'Fake model 1' },
     {id: 'my-fake-id-2, name: 'Fake model 2' }
  ])
})

it ('foo bar', () => {
  // do something with that collection
})
```

**Comment by n1arash** [comment]
Thank you this is nice solution :+1:

**Comment by andresgutgon** [comment]
Can we close the issue @n1arash ?

**Comment by n1arash** [comment]
yes thank you for helping !

**Comment by andresgutgon** [comment]
Welcome :)
