### ISSUE TITLE
customizable rpc url

### ISSUE THREAD

**Issue by FPurchess** [masylum/mobx-rest#41]
The rpc url building is currently deeply baked into the rpc method (see https://github.com/masylum/mobx-rest/blob/master/src/Collection.js#L333). The current implementation raises problems when working with APIs that have urls with trailing slashes. It would be great to refactor the url building into a separate method in order of giving more control over how they are built.

**Comment by geclos** [comment]
Hi @FPurchess,

addressing your issue in the upcoming mobx@3.0.0. Do you have any preferred implementation? So far I went with this signature:
```js
rpc (endpoint: string | { rootUrl: string }, options?: {}, label?: string = 'fetching'): Request {
```
So that you could pass an optional object with a complete rootUrl to use instead of the endpoint-baking stuff we do behind the scenes.
