### ISSUE TITLE
Support of mobX 4

### ISSUE THREAD

**Issue by gcollomb** [masylum/mobx-rest#45]
Hi,

do you expect to suport mobx v4.x ?

I supose that my previous issues (#43) was due to my use of mobx 4.3.0

Furthermore, .find() and .filter() in Collections don't work.

**Comment by dbrody** [comment]
@gcollomb - I also noticed the issue with collections. I filed a new issue in #46

**Comment by njdancer** [comment]
Not sure if this is still the case. The package.json now lists Mobx 5 as a dependency.

```javascript
"peerDependencies": {
  "mobx": "5.9.4"
},
```

That said I had issues getting this working and unfortunately went in a different direction so can't confirm that this actually works.

**Comment by masylum** [comment]
This is already resolved. `mobx-rest` works with mobx `5.9.4` now.
Which issues did you find @njdancer ?

**Comment by njdancer** [comment]
@masylum I don’t have a reproduction I’m afraid. They could have been issues with my code. I have strict mode enabled and was getting warnings about computed values being accessed outside a reactive context. I wasn’t certain of the compatibility of your project and for time reasons couldn’t really afford to debug the issue. I ended up rolling something myself which is far less polished then what you have but it at least removed the abstraction layer making it easier to get working In this instance. What you’ve written looks great though and hopefully I’ll have a chance to try it again.

I mostly posted the comment in case there were compatibility issues and someone found themselves in the same situation. Given your confirmation I would suggest closing this issue to avoid any confusion. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
