### ISSUE TITLE
Collection's .find() and .filter() dont work

### ISSUE THREAD

**Issue by dbrody** [masylum/mobx-rest#46]
I'm using

```
"mobx": "^5.0.2",
"mobx-react": "^5.2.3",
"mobx-rest": "^2.2.5",
"mobx-rest-axios-adapter": "^2.1.1",
"mobx-utils": "^5.0.0",
```

And I also noticed that `.find()` and `.filter()` in Collections dont' work.

My workaround was built off of @gcollomb suggestion - I placed this at the top of my app:

```javascript
// Fix for collections
import { ObservableMap} from 'mobx';
ObservableMap.prototype.toJS = function(){
    var _this = this;
    var res = {};
    const keys = Array.from(this.keys());
    keys.forEach(function (key) { return res[key]= _this.get(key); });
    return res;
} 
```

Wondering if this is a known issue or why this is like this.

**Comment by masylum** [comment]
are you still facing this issue? Now it works and uses indexing for fast retrieval of models.
