### ISSUE TITLE
Count method without fetching all the collection

### ISSUE THREAD

**Issue by jkeruzec** [masylum/mobx-rest#49]
Is it possible to have a count method for collection (GET /collection/count) to count whitout fetching all collection ?

Maybe in V3.0.0 of mbox-rest ?

Thanks !

**Comment by jkeruzec** [comment]
Ok great, I can use the apiClient to fetch my data.

I wanted also to have the information like an observable data ?

For example : 
I use the count to display information on one part of my page using collection information

In another part of my page, I modify this collection and I want to trigger the "observable event" to refresh the collection count ... 

Can you help on this / Is there any trick to link collection/Models and this count part ?

Thanks !

**Comment by masylum** [comment]
yep, using reactions is probably the best way to do so. After all, `mobx-rest` only takes care of the REST conventions and the API abstraction. Anything else is up to you.

**Comment by jkeruzec** [comment]
I finaly used models length and reaction and worked like a charm!
Thanks !
