### ISSUE TITLE
Support for primary key

### ISSUE THREAD

**Issue by thomasandersen** [masylum/mobx-rest#6]
Hi

Thank you for a nice library!

Would it be an idea to have support for primaryKey in Model?
Right now it is assumed that model attributes has `id` as primary key.

eg.:

```
class Fish extends Model {
  get primaryKey() {
    return 'key'; 
  }
}
```

**Comment by jamesholcomb** [comment]
+1 as my responses return "_id" from `mongoose` lean models.

**Comment by masylum** [comment]
That would be great!
PRs are welcome 😄

**Comment by masylum** [comment]
Added support for `primaryKey` and also improved the docs 💪. Enjoy!
