### ISSUE TITLE
[DOC] isEmpty is no longer a method but just a field

### ISSUE THREAD

**Issue by jkeruzec** [masylum/mobx-rest#64]
Please fix the doc, as empty is no longer a function.

isEmpty: boolean
Helper method that asks the collection whether there is any model in it.

Example:

const promise = usersCollection.fetch()
usersCollection.isEmpty() // => true
await promise
usersCollection.isEmpty() // => false
usersCollection.models.length // => 10

**Comment by geclos** [comment]
Hi!

thanks for noticing, fixing it here: https://github.com/masylum/mobx-rest/pull/65

**Comment by geclos** [comment]
Fixed. Closing issue.
