### ISSUE TITLE
V3.0.6 : Mobx strict mode issue fetch won't work

### ISSUE THREAD

**Issue by jkeruzec** [masylum/mobx-rest#66]
I'm using mobx-rest for over 1 year now and since I migrate on V3.0.6, collections are not working anymore.
I think it's because of Mobx migration and internal issue : 

My (simple) code that used to work before : 
``` js
@withStyles(styles, {withTheme: true})
@withRouter
@observer
class ModulesPage extends React.Component {
    
    currentModule = ""
    
   
    componentDidMount () {
        const moduleName = this.props.match.path.split("/")[1];
        // Specific module name
        if(moduleName !== "") {
            modulesCollection.fetchByModuleName(moduleName);
            this.currentModule = moduleName;
        // Root module
        } else {
            modulesCollection.fetch();
        }
        
    }
    
   
    render() {
        
       const {classes} = this.props;
       const collec = modulesCollection;
       
       if(collec.isRequest('fetching')) {
           return "";
       }
       
       let moduleItems = collec.models.slice().sort((a, b) => a.get('position') - b.get('position')).map((item) => <ModuleItem classes={classes} key={item.get('name')} name={item.get('name')} title={item.get('value')} description={item.get('description')} />);
       
       // Fetch child for parent module
       if(this.currentModule !== "" && collec.models.length !== 0) {
           moduleItems = collec.at(0).get('children').map((item) => <ModuleItem relativePath={this.currentModule} classes={classes} key={item.name} name={item.name} title={item.value} description={item.description} />);
       }
       
       return (
               <React.Fragment>
                   {moduleItems}
               </React.Fragment>
       );
    }
    
}

export default ModulesPage;
```
When  my collection is loading : 
![image](https://user-images.githubusercontent.com/3499632/59271956-34f39c00-8c55-11e9-80af-dfa237be5855.png)

When it's resolving : 
![image](https://user-images.githubusercontent.com/3499632/59272055-7126fc80-8c55-11e9-97ad-099a08e2142a.png)

I precise that I'm using
https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md#enforceactions
with "observed"

Thanks,

**Comment by jkeruzec** [comment]
Edit, It works with `configure({ enforceActions: "never" });` instead of `configure({ enforceActions: "observed" });` but I would not like to use this too much permissive configuration ...

**Comment by jkeruzec** [comment]
Up! @masylum

**Comment by badgeek** [comment]
@masylum i still got this error

`Dynamic page loading failed Error: "[mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: Cards@5.requests"`

and

`Unhandled promise rejection Error: "[mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: Cards@5.requests"`

using above similar code..

library version:

`    "mobx-rest": "^5.0.5",`

**Comment by masylum** [comment]
interesting, do you have any more clues where is this happening? We don't run mobx in strict-mode so a little help would be great!

**Comment by badgeek** [comment]
@masylum i ran it with stric-mode and change it to observe and it works, thanks!

**Comment by jkeruzec** [comment]
Sorry guys for that, I saw that it wasn't working for me either. I changed few things and now it's OK. I will republish a new PR with some new actions to comply with enforceActions 'always"
