### ISSUE TITLE
Cannot remove data from collection

### ISSUE THREAD

**Issue by rainx** [masylum/mobx-rest#90]
I tried to use Collection's remove method and I wanna remove specified entries from the collection. I found that this method is only removing data from the current object but not sending request to the backend. 

so how can I sync these changes to the backend after that?

can I remove (from server-side) the entries directly by the method on the Collection?

```
someCollection.remove(["id1, "id2"]);
```

**Comment by masylum** [comment]
We don't have a bulk deletion operation. In this case you should call `destroy` to those models

**Comment by rainx** [comment]
> We don't have a bulk deletion operation. In this case you should call `destroy` to those models

Thanks
