### ISSUE TITLE
IE11 Support question

### ISSUE THREAD

**Issue by rainx** [masylum/mobx-rest#92]
I just noticed that the dependency of MobX is 5. and does that mean MobX Rest is no longer support IE11 now? and if not. is there any workarounds to support IE11?

**Comment by rainx** [comment]
I mean . can I use the resolutions feature of package manager (https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to enforce using MobX4 in my project.  actually, my project has already been using MobX 4 as dependency for IE11 support.

**Comment by masylum** [comment]
Hi @rainx that's right. We've updated the dependency to mobx5 recently and they do not support IE11 anymore. I'm not sure what's the best way to workaround that :/

**Comment by andresgutgon** [comment]
IE11 support ends this year on October https://twitter.com/swyx/status/1260627626739130369?s=19

Maybe you could considere not giving support

**Comment by rainx** [comment]
Thanks, @masylum @andresgutgon , thanks for your advice.

**Comment by rainx** [comment]
Still cannot persuade our production team to drop IE 11 support now. so I found a workaround to run the mobx-rest under IE 11.

1. Force use mobx to @4 by adding the following code on `packages.json`
```JSON
{
 "packages": {
    "other packages": n,
    "mobx": "4",
    "mobx-rest": "^7.0.1",
    "mobx-rest-axios-adapter": "^2.1.1"
  },
  "resolutions": {
    "mobx-rest/mobx": "4"
  },
}
```
2. use babel-env to transpile codes (add some polyfills)  for IE11. especially, must patch Map.set() ( IE 11 will return undefined instead of the Map itself)

3. patch `mobx-rest-axios-adapter` to make it works for IE 11. (IE 11 not transform json to object )

here are the code snippets I used
```TypeScript
  import createAdapter from "mobx-rest-axios-adapter";

  const clonedDefaultHttpClient = axios.create(defaultHttpClient.defaults);
  //......
  // ....
  clonedDefaultHttpClient.defaults.responseType = "json";

   clonedDefaultHttpClient.defaults.transformResponse = [
    (data): typeof data => {
      // Hack for IE 11 https://github.com/axios/axios/pull/1697
      if (!!window.ActiveXObject || "ActiveXObject" in window) {
        if (typeof data === "string") {
          try {
            // eslint-disable-next-line no-param-reassign
            data = JSON.parse(data);
          } catch (e) {
            /* Ignore */
          }
        }
      }
      // .. other codes..
      return data;
    },
  ];

  (clonedDefaultHttpClient as AxiosInstance & {
    CancelToken: typeof axios.CancelToken;
  }).CancelToken = axios.CancelToken;
  apiClient(createAdapter(clonedDefaultHttpClient));
```
