### ISSUE TITLE
Always throw error to the caller if the apiClient throws error.

### ISSUE THREAD

**Issue by rainx** [masylum/mobx-rest#93]
Hi @masylum 

In the current implementation. we ignore the error within the Model and Collection on rest operation. for example.

in the Modal.ts

```
  @action
  fetch ({ data, ...otherOptions }: { data?: {} } = {}): Request {
...
      .catch(_error => {}) // do nothing
...
  }
```

we catch the network error and do nothing.

In some cases. we need to catch the specified error in the upper scope of the Mobx Rest and process the specified logic for the error. 

so is it possible to throw all the errors to the upper scope and let the user decide how to process it. 

or, if it is too breaking changes. can we add an option to the model or the collection class to optional enable this feature.

such as 

```
catch(_error => {
   ... other logic
    if (this.enableRaisingAllErrors) {
        throw(_errors) // or return Promise.reject(_errors);
    }
}
```

do you think that works?

Thanks

**Comment by rainx** [comment]
Sorry, that is my mistake, currently, the library works well

**Comment by andresgutgon** [comment]
Glad you could find the issue :)
