### ISSUE TITLE
MobX 6 support ?

### ISSUE THREAD

**Issue by rainx** [masylum/mobx-rest#95]
Hi @masylum 

Is there a plan that the MobX Rest project to work with the newly released MobX 6, coz our project is currently integrated with the MobX Rest, so I just wanna know the timeline and upcoming breaking changes? 

I just tried to test on the current project. I found there are two mainly breaking changes.

1. `runInAciton` currently always take only one parameter.,  that is easy to fix , just wrapped a action function inside
```TypeScript
        runInAction('save success', () => {})
to 
        runInAction(action('save success', () => {})
```
2. `toJS `no longer takes any options. It no longer converts Maps and Sets to plain data structures.

this above change breaks the test code of MobX Rest, we also heavily used toJS() as a plain object in our project. so I curious what is the plan that the MobX Rest developer, a backward-compatible toJS() on Models nad Collections or follow the MobX's change?

Thanks

**Comment by masylum** [comment]
We haven't upgraded yet, feel free to contribute :)

**Comment by rainx** [comment]
@masylum 

Just sent a PR #96. Please review it.
